services:
  reservations:
    build:
      context: .
      dockerfile: ./app/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
