services:
  reservations:
    container_name: sleeper-reservations-one
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
  auth:
    container_name: sleeper-auth-one
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: sleeper-mongo-one
    image: mongo
    ports:
      - '27017:27017'
    # volumes:
    #   - ./data:/data/db  // Using this docker volume like this will create a data folder in the current root directory
    volumes:
      - mongo:/data/db
      # - mongo:/data/db Using this docker volume like this will create a data folder in the current root directory and managed by docker
volumes:
  mongo: {}
